/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as LayoutImport } from "./routes/_layout"
import { Route as LayoutIndexImport } from "./routes/_layout/index"
import { Route as AuthAuthLayoutImport } from "./routes/auth/_auth-layout"
import { Route as LayoutHotelsLayoutImport } from "./routes/_layout/_hotels-layout"
import { Route as AuthAuthLayoutIndexImport } from "./routes/auth/_auth-layout/index"
import { Route as AuthAuthLayoutLoginImport } from "./routes/auth/_auth-layout/login"
import { Route as LayoutHotelsLayoutProfileImport } from "./routes/_layout/_hotels-layout/profile"
import { Route as LayoutHotelsLayoutPaymentsImport } from "./routes/_layout/_hotels-layout/payments"
import { Route as LayoutHotelsLayoutLocationsImport } from "./routes/_layout/_hotels-layout/locations"
import { Route as LayoutHotelsLayoutHotelsImport } from "./routes/_layout/_hotels-layout/hotels_"
import { Route as LayoutHotelsLayoutCategoriesImport } from "./routes/_layout/_hotels-layout/categories"
import { Route as LayoutHotelsLayoutAmenitiesImport } from "./routes/_layout/_hotels-layout/amenities"
import { Route as LayoutHotelsHotelSlugHotelLayoutImport } from "./routes/_layout/hotels.$hotelSlug/_hotel-layout"
import { Route as LayoutHotelsHotelSlugHotelLayoutRoomsIndexImport } from "./routes/_layout/hotels.$hotelSlug/_hotel-layout/rooms/index"
import { Route as LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutImport } from "./routes/_layout/hotels.$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout"
import { Route as LayoutHotelsHotelSlugHotelLayoutRoomsRoomIdIndexImport } from "./routes/_layout/hotels.$hotelSlug/_hotel-layout/rooms/$roomId/index"
import { Route as LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutIndexImport } from "./routes/_layout/hotels.$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/index"
import { Route as LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRulesImport } from "./routes/_layout/hotels.$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/rules"
import { Route as LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutReviewsImport } from "./routes/_layout/hotels.$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/reviews"
import { Route as LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutAmenitiesImport } from "./routes/_layout/hotels.$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/amenities"

// Create Virtual Routes

const AuthImport = createFileRoute("/auth")()
const LayoutHotelsHotelSlugImport = createFileRoute(
  "/_layout/hotels/$hotelSlug",
)()
const LayoutHotelsHotelSlugHotelLayouthotelInfoImport = createFileRoute(
  "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)",
)()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: "/_layout",
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LayoutRoute,
} as any)

const AuthAuthLayoutRoute = AuthAuthLayoutImport.update({
  id: "/_auth-layout",
  getParentRoute: () => AuthRoute,
} as any)

const LayoutHotelsLayoutRoute = LayoutHotelsLayoutImport.update({
  id: "/_hotels-layout",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHotelsHotelSlugRoute = LayoutHotelsHotelSlugImport.update({
  id: "/hotels/$hotelSlug",
  path: "/hotels/$hotelSlug",
  getParentRoute: () => LayoutRoute,
} as any)

const AuthAuthLayoutIndexRoute = AuthAuthLayoutIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)

const AuthAuthLayoutLoginRoute = AuthAuthLayoutLoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)

const LayoutHotelsLayoutProfileRoute = LayoutHotelsLayoutProfileImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => LayoutHotelsLayoutRoute,
} as any)

const LayoutHotelsLayoutPaymentsRoute = LayoutHotelsLayoutPaymentsImport.update(
  {
    id: "/payments",
    path: "/payments",
    getParentRoute: () => LayoutHotelsLayoutRoute,
  } as any,
)

const LayoutHotelsLayoutLocationsRoute =
  LayoutHotelsLayoutLocationsImport.update({
    id: "/locations",
    path: "/locations",
    getParentRoute: () => LayoutHotelsLayoutRoute,
  } as any)

const LayoutHotelsLayoutHotelsRoute = LayoutHotelsLayoutHotelsImport.update({
  id: "/hotels_",
  path: "/hotels",
  getParentRoute: () => LayoutHotelsLayoutRoute,
} as any)

const LayoutHotelsLayoutCategoriesRoute =
  LayoutHotelsLayoutCategoriesImport.update({
    id: "/categories",
    path: "/categories",
    getParentRoute: () => LayoutHotelsLayoutRoute,
  } as any)

const LayoutHotelsLayoutAmenitiesRoute =
  LayoutHotelsLayoutAmenitiesImport.update({
    id: "/amenities",
    path: "/amenities",
    getParentRoute: () => LayoutHotelsLayoutRoute,
  } as any)

const LayoutHotelsHotelSlugHotelLayoutRoute =
  LayoutHotelsHotelSlugHotelLayoutImport.update({
    id: "/_hotel-layout",
    getParentRoute: () => LayoutHotelsHotelSlugRoute,
  } as any)

const LayoutHotelsHotelSlugHotelLayouthotelInfoRoute =
  LayoutHotelsHotelSlugHotelLayouthotelInfoImport.update({
    id: "/(hotel-info)",
    getParentRoute: () => LayoutHotelsHotelSlugHotelLayoutRoute,
  } as any)

const LayoutHotelsHotelSlugHotelLayoutRoomsIndexRoute =
  LayoutHotelsHotelSlugHotelLayoutRoomsIndexImport.update({
    id: "/rooms/",
    path: "/rooms/",
    getParentRoute: () => LayoutHotelsHotelSlugHotelLayoutRoute,
  } as any)

const LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRoute =
  LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutImport.update({
    id: "/_hotel-info-layout",
    getParentRoute: () => LayoutHotelsHotelSlugHotelLayouthotelInfoRoute,
  } as any)

const LayoutHotelsHotelSlugHotelLayoutRoomsRoomIdIndexRoute =
  LayoutHotelsHotelSlugHotelLayoutRoomsRoomIdIndexImport.update({
    id: "/rooms/$roomId/",
    path: "/rooms/$roomId/",
    getParentRoute: () => LayoutHotelsHotelSlugHotelLayoutRoute,
  } as any)

const LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutIndexRoute =
  LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutIndexImport.update({
    id: "/",
    path: "/",
    getParentRoute: () =>
      LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRoute,
  } as any)

const LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRulesRoute =
  LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRulesImport.update({
    id: "/rules",
    path: "/rules",
    getParentRoute: () =>
      LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRoute,
  } as any)

const LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutReviewsRoute =
  LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutReviewsImport.update({
    id: "/reviews",
    path: "/reviews",
    getParentRoute: () =>
      LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRoute,
  } as any)

const LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutAmenitiesRoute =
  LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutAmenitiesImport.update(
    {
      id: "/amenities",
      path: "/amenities",
      getParentRoute: () =>
        LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    "/_layout/_hotels-layout": {
      id: "/_layout/_hotels-layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof LayoutHotelsLayoutImport
      parentRoute: typeof LayoutImport
    }
    "/auth": {
      id: "/auth"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    "/auth/_auth-layout": {
      id: "/auth/_auth-layout"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthAuthLayoutImport
      parentRoute: typeof AuthRoute
    }
    "/_layout/": {
      id: "/_layout/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/_hotels-layout/amenities": {
      id: "/_layout/_hotels-layout/amenities"
      path: "/amenities"
      fullPath: "/amenities"
      preLoaderRoute: typeof LayoutHotelsLayoutAmenitiesImport
      parentRoute: typeof LayoutHotelsLayoutImport
    }
    "/_layout/_hotels-layout/categories": {
      id: "/_layout/_hotels-layout/categories"
      path: "/categories"
      fullPath: "/categories"
      preLoaderRoute: typeof LayoutHotelsLayoutCategoriesImport
      parentRoute: typeof LayoutHotelsLayoutImport
    }
    "/_layout/_hotels-layout/hotels_": {
      id: "/_layout/_hotels-layout/hotels_"
      path: "/hotels"
      fullPath: "/hotels"
      preLoaderRoute: typeof LayoutHotelsLayoutHotelsImport
      parentRoute: typeof LayoutHotelsLayoutImport
    }
    "/_layout/_hotels-layout/locations": {
      id: "/_layout/_hotels-layout/locations"
      path: "/locations"
      fullPath: "/locations"
      preLoaderRoute: typeof LayoutHotelsLayoutLocationsImport
      parentRoute: typeof LayoutHotelsLayoutImport
    }
    "/_layout/_hotels-layout/payments": {
      id: "/_layout/_hotels-layout/payments"
      path: "/payments"
      fullPath: "/payments"
      preLoaderRoute: typeof LayoutHotelsLayoutPaymentsImport
      parentRoute: typeof LayoutHotelsLayoutImport
    }
    "/_layout/_hotels-layout/profile": {
      id: "/_layout/_hotels-layout/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof LayoutHotelsLayoutProfileImport
      parentRoute: typeof LayoutHotelsLayoutImport
    }
    "/auth/_auth-layout/login": {
      id: "/auth/_auth-layout/login"
      path: "/login"
      fullPath: "/auth/login"
      preLoaderRoute: typeof AuthAuthLayoutLoginImport
      parentRoute: typeof AuthAuthLayoutImport
    }
    "/auth/_auth-layout/": {
      id: "/auth/_auth-layout/"
      path: "/"
      fullPath: "/auth/"
      preLoaderRoute: typeof AuthAuthLayoutIndexImport
      parentRoute: typeof AuthAuthLayoutImport
    }
    "/_layout/hotels/$hotelSlug": {
      id: "/_layout/hotels/$hotelSlug"
      path: "/hotels/$hotelSlug"
      fullPath: "/hotels/$hotelSlug"
      preLoaderRoute: typeof LayoutHotelsHotelSlugImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/hotels/$hotelSlug/_hotel-layout": {
      id: "/_layout/hotels/$hotelSlug/_hotel-layout"
      path: "/hotels/$hotelSlug"
      fullPath: "/hotels/$hotelSlug"
      preLoaderRoute: typeof LayoutHotelsHotelSlugHotelLayoutImport
      parentRoute: typeof LayoutHotelsHotelSlugRoute
    }
    "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)": {
      id: "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)"
      path: "/"
      fullPath: "/hotels/$hotelSlug/"
      preLoaderRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoImport
      parentRoute: typeof LayoutHotelsHotelSlugHotelLayoutImport
    }
    "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout": {
      id: "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout"
      path: "/"
      fullPath: "/hotels/$hotelSlug/"
      preLoaderRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutImport
      parentRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoRoute
    }
    "/_layout/hotels/$hotelSlug/_hotel-layout/rooms/": {
      id: "/_layout/hotels/$hotelSlug/_hotel-layout/rooms/"
      path: "/rooms"
      fullPath: "/hotels/$hotelSlug/rooms"
      preLoaderRoute: typeof LayoutHotelsHotelSlugHotelLayoutRoomsIndexImport
      parentRoute: typeof LayoutHotelsHotelSlugHotelLayoutImport
    }
    "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/amenities": {
      id: "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/amenities"
      path: "/amenities"
      fullPath: "/hotels/$hotelSlug/amenities"
      preLoaderRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutAmenitiesImport
      parentRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutImport
    }
    "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/reviews": {
      id: "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/reviews"
      path: "/reviews"
      fullPath: "/hotels/$hotelSlug/reviews"
      preLoaderRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutReviewsImport
      parentRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutImport
    }
    "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/rules": {
      id: "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/rules"
      path: "/rules"
      fullPath: "/hotels/$hotelSlug/rules"
      preLoaderRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRulesImport
      parentRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutImport
    }
    "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/": {
      id: "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/"
      path: "/"
      fullPath: "/hotels/$hotelSlug/"
      preLoaderRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutIndexImport
      parentRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutImport
    }
    "/_layout/hotels/$hotelSlug/_hotel-layout/rooms/$roomId/": {
      id: "/_layout/hotels/$hotelSlug/_hotel-layout/rooms/$roomId/"
      path: "/rooms/$roomId"
      fullPath: "/hotels/$hotelSlug/rooms/$roomId"
      preLoaderRoute: typeof LayoutHotelsHotelSlugHotelLayoutRoomsRoomIdIndexImport
      parentRoute: typeof LayoutHotelsHotelSlugHotelLayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutHotelsLayoutRouteChildren {
  LayoutHotelsLayoutAmenitiesRoute: typeof LayoutHotelsLayoutAmenitiesRoute
  LayoutHotelsLayoutCategoriesRoute: typeof LayoutHotelsLayoutCategoriesRoute
  LayoutHotelsLayoutHotelsRoute: typeof LayoutHotelsLayoutHotelsRoute
  LayoutHotelsLayoutLocationsRoute: typeof LayoutHotelsLayoutLocationsRoute
  LayoutHotelsLayoutPaymentsRoute: typeof LayoutHotelsLayoutPaymentsRoute
  LayoutHotelsLayoutProfileRoute: typeof LayoutHotelsLayoutProfileRoute
}

const LayoutHotelsLayoutRouteChildren: LayoutHotelsLayoutRouteChildren = {
  LayoutHotelsLayoutAmenitiesRoute: LayoutHotelsLayoutAmenitiesRoute,
  LayoutHotelsLayoutCategoriesRoute: LayoutHotelsLayoutCategoriesRoute,
  LayoutHotelsLayoutHotelsRoute: LayoutHotelsLayoutHotelsRoute,
  LayoutHotelsLayoutLocationsRoute: LayoutHotelsLayoutLocationsRoute,
  LayoutHotelsLayoutPaymentsRoute: LayoutHotelsLayoutPaymentsRoute,
  LayoutHotelsLayoutProfileRoute: LayoutHotelsLayoutProfileRoute,
}

const LayoutHotelsLayoutRouteWithChildren =
  LayoutHotelsLayoutRoute._addFileChildren(LayoutHotelsLayoutRouteChildren)

interface LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRouteChildren {
  LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutAmenitiesRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutAmenitiesRoute
  LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutReviewsRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutReviewsRoute
  LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRulesRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRulesRoute
  LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutIndexRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutIndexRoute
}

const LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRouteChildren: LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRouteChildren =
  {
    LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutAmenitiesRoute:
      LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutAmenitiesRoute,
    LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutReviewsRoute:
      LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutReviewsRoute,
    LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRulesRoute:
      LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRulesRoute,
    LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutIndexRoute:
      LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutIndexRoute,
  }

const LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRouteWithChildren =
  LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRoute._addFileChildren(
    LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRouteChildren,
  )

interface LayoutHotelsHotelSlugHotelLayouthotelInfoRouteChildren {
  LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRouteWithChildren
}

const LayoutHotelsHotelSlugHotelLayouthotelInfoRouteChildren: LayoutHotelsHotelSlugHotelLayouthotelInfoRouteChildren =
  {
    LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRoute:
      LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRouteWithChildren,
  }

const LayoutHotelsHotelSlugHotelLayouthotelInfoRouteWithChildren =
  LayoutHotelsHotelSlugHotelLayouthotelInfoRoute._addFileChildren(
    LayoutHotelsHotelSlugHotelLayouthotelInfoRouteChildren,
  )

interface LayoutHotelsHotelSlugHotelLayoutRouteChildren {
  LayoutHotelsHotelSlugHotelLayouthotelInfoRoute: typeof LayoutHotelsHotelSlugHotelLayouthotelInfoRouteWithChildren
  LayoutHotelsHotelSlugHotelLayoutRoomsIndexRoute: typeof LayoutHotelsHotelSlugHotelLayoutRoomsIndexRoute
  LayoutHotelsHotelSlugHotelLayoutRoomsRoomIdIndexRoute: typeof LayoutHotelsHotelSlugHotelLayoutRoomsRoomIdIndexRoute
}

const LayoutHotelsHotelSlugHotelLayoutRouteChildren: LayoutHotelsHotelSlugHotelLayoutRouteChildren =
  {
    LayoutHotelsHotelSlugHotelLayouthotelInfoRoute:
      LayoutHotelsHotelSlugHotelLayouthotelInfoRouteWithChildren,
    LayoutHotelsHotelSlugHotelLayoutRoomsIndexRoute:
      LayoutHotelsHotelSlugHotelLayoutRoomsIndexRoute,
    LayoutHotelsHotelSlugHotelLayoutRoomsRoomIdIndexRoute:
      LayoutHotelsHotelSlugHotelLayoutRoomsRoomIdIndexRoute,
  }

const LayoutHotelsHotelSlugHotelLayoutRouteWithChildren =
  LayoutHotelsHotelSlugHotelLayoutRoute._addFileChildren(
    LayoutHotelsHotelSlugHotelLayoutRouteChildren,
  )

interface LayoutHotelsHotelSlugRouteChildren {
  LayoutHotelsHotelSlugHotelLayoutRoute: typeof LayoutHotelsHotelSlugHotelLayoutRouteWithChildren
}

const LayoutHotelsHotelSlugRouteChildren: LayoutHotelsHotelSlugRouteChildren = {
  LayoutHotelsHotelSlugHotelLayoutRoute:
    LayoutHotelsHotelSlugHotelLayoutRouteWithChildren,
}

const LayoutHotelsHotelSlugRouteWithChildren =
  LayoutHotelsHotelSlugRoute._addFileChildren(
    LayoutHotelsHotelSlugRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutHotelsLayoutRoute: typeof LayoutHotelsLayoutRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutHotelsHotelSlugRoute: typeof LayoutHotelsHotelSlugRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutHotelsLayoutRoute: LayoutHotelsLayoutRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutHotelsHotelSlugRoute: LayoutHotelsHotelSlugRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthAuthLayoutRouteChildren {
  AuthAuthLayoutLoginRoute: typeof AuthAuthLayoutLoginRoute
  AuthAuthLayoutIndexRoute: typeof AuthAuthLayoutIndexRoute
}

const AuthAuthLayoutRouteChildren: AuthAuthLayoutRouteChildren = {
  AuthAuthLayoutLoginRoute: AuthAuthLayoutLoginRoute,
  AuthAuthLayoutIndexRoute: AuthAuthLayoutIndexRoute,
}

const AuthAuthLayoutRouteWithChildren = AuthAuthLayoutRoute._addFileChildren(
  AuthAuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthAuthLayoutRoute: typeof AuthAuthLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLayoutRoute: AuthAuthLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  "": typeof LayoutHotelsLayoutRouteWithChildren
  "/auth": typeof AuthAuthLayoutRouteWithChildren
  "/": typeof LayoutIndexRoute
  "/amenities": typeof LayoutHotelsLayoutAmenitiesRoute
  "/categories": typeof LayoutHotelsLayoutCategoriesRoute
  "/hotels": typeof LayoutHotelsLayoutHotelsRoute
  "/locations": typeof LayoutHotelsLayoutLocationsRoute
  "/payments": typeof LayoutHotelsLayoutPaymentsRoute
  "/profile": typeof LayoutHotelsLayoutProfileRoute
  "/auth/login": typeof AuthAuthLayoutLoginRoute
  "/auth/": typeof AuthAuthLayoutIndexRoute
  "/hotels/$hotelSlug": typeof LayoutHotelsHotelSlugHotelLayoutRouteWithChildren
  "/hotels/$hotelSlug/": typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutIndexRoute
  "/hotels/$hotelSlug/rooms": typeof LayoutHotelsHotelSlugHotelLayoutRoomsIndexRoute
  "/hotels/$hotelSlug/amenities": typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutAmenitiesRoute
  "/hotels/$hotelSlug/reviews": typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutReviewsRoute
  "/hotels/$hotelSlug/rules": typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRulesRoute
  "/hotels/$hotelSlug/rooms/$roomId": typeof LayoutHotelsHotelSlugHotelLayoutRoomsRoomIdIndexRoute
}

export interface FileRoutesByTo {
  "": typeof LayoutHotelsLayoutRouteWithChildren
  "/auth": typeof AuthAuthLayoutIndexRoute
  "/": typeof LayoutIndexRoute
  "/amenities": typeof LayoutHotelsLayoutAmenitiesRoute
  "/categories": typeof LayoutHotelsLayoutCategoriesRoute
  "/hotels": typeof LayoutHotelsLayoutHotelsRoute
  "/locations": typeof LayoutHotelsLayoutLocationsRoute
  "/payments": typeof LayoutHotelsLayoutPaymentsRoute
  "/profile": typeof LayoutHotelsLayoutProfileRoute
  "/auth/login": typeof AuthAuthLayoutLoginRoute
  "/hotels/$hotelSlug": typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutIndexRoute
  "/hotels/$hotelSlug/rooms": typeof LayoutHotelsHotelSlugHotelLayoutRoomsIndexRoute
  "/hotels/$hotelSlug/amenities": typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutAmenitiesRoute
  "/hotels/$hotelSlug/reviews": typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutReviewsRoute
  "/hotels/$hotelSlug/rules": typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRulesRoute
  "/hotels/$hotelSlug/rooms/$roomId": typeof LayoutHotelsHotelSlugHotelLayoutRoomsRoomIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/_layout": typeof LayoutRouteWithChildren
  "/_layout/_hotels-layout": typeof LayoutHotelsLayoutRouteWithChildren
  "/auth": typeof AuthRouteWithChildren
  "/auth/_auth-layout": typeof AuthAuthLayoutRouteWithChildren
  "/_layout/": typeof LayoutIndexRoute
  "/_layout/_hotels-layout/amenities": typeof LayoutHotelsLayoutAmenitiesRoute
  "/_layout/_hotels-layout/categories": typeof LayoutHotelsLayoutCategoriesRoute
  "/_layout/_hotels-layout/hotels_": typeof LayoutHotelsLayoutHotelsRoute
  "/_layout/_hotels-layout/locations": typeof LayoutHotelsLayoutLocationsRoute
  "/_layout/_hotels-layout/payments": typeof LayoutHotelsLayoutPaymentsRoute
  "/_layout/_hotels-layout/profile": typeof LayoutHotelsLayoutProfileRoute
  "/auth/_auth-layout/login": typeof AuthAuthLayoutLoginRoute
  "/auth/_auth-layout/": typeof AuthAuthLayoutIndexRoute
  "/_layout/hotels/$hotelSlug": typeof LayoutHotelsHotelSlugRouteWithChildren
  "/_layout/hotels/$hotelSlug/_hotel-layout": typeof LayoutHotelsHotelSlugHotelLayoutRouteWithChildren
  "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)": typeof LayoutHotelsHotelSlugHotelLayouthotelInfoRouteWithChildren
  "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout": typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRouteWithChildren
  "/_layout/hotels/$hotelSlug/_hotel-layout/rooms/": typeof LayoutHotelsHotelSlugHotelLayoutRoomsIndexRoute
  "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/amenities": typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutAmenitiesRoute
  "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/reviews": typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutReviewsRoute
  "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/rules": typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutRulesRoute
  "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/": typeof LayoutHotelsHotelSlugHotelLayouthotelInfoHotelInfoLayoutIndexRoute
  "/_layout/hotels/$hotelSlug/_hotel-layout/rooms/$roomId/": typeof LayoutHotelsHotelSlugHotelLayoutRoomsRoomIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ""
    | "/auth"
    | "/"
    | "/amenities"
    | "/categories"
    | "/hotels"
    | "/locations"
    | "/payments"
    | "/profile"
    | "/auth/login"
    | "/auth/"
    | "/hotels/$hotelSlug"
    | "/hotels/$hotelSlug/"
    | "/hotels/$hotelSlug/rooms"
    | "/hotels/$hotelSlug/amenities"
    | "/hotels/$hotelSlug/reviews"
    | "/hotels/$hotelSlug/rules"
    | "/hotels/$hotelSlug/rooms/$roomId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | ""
    | "/auth"
    | "/"
    | "/amenities"
    | "/categories"
    | "/hotels"
    | "/locations"
    | "/payments"
    | "/profile"
    | "/auth/login"
    | "/hotels/$hotelSlug"
    | "/hotels/$hotelSlug/rooms"
    | "/hotels/$hotelSlug/amenities"
    | "/hotels/$hotelSlug/reviews"
    | "/hotels/$hotelSlug/rules"
    | "/hotels/$hotelSlug/rooms/$roomId"
  id:
    | "__root__"
    | "/_layout"
    | "/_layout/_hotels-layout"
    | "/auth"
    | "/auth/_auth-layout"
    | "/_layout/"
    | "/_layout/_hotels-layout/amenities"
    | "/_layout/_hotels-layout/categories"
    | "/_layout/_hotels-layout/hotels_"
    | "/_layout/_hotels-layout/locations"
    | "/_layout/_hotels-layout/payments"
    | "/_layout/_hotels-layout/profile"
    | "/auth/_auth-layout/login"
    | "/auth/_auth-layout/"
    | "/_layout/hotels/$hotelSlug"
    | "/_layout/hotels/$hotelSlug/_hotel-layout"
    | "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)"
    | "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout"
    | "/_layout/hotels/$hotelSlug/_hotel-layout/rooms/"
    | "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/amenities"
    | "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/reviews"
    | "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/rules"
    | "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/"
    | "/_layout/hotels/$hotelSlug/_hotel-layout/rooms/$roomId/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/auth"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_hotels-layout",
        "/_layout/",
        "/_layout/hotels/$hotelSlug"
      ]
    },
    "/_layout/_hotels-layout": {
      "filePath": "_layout/_hotels-layout.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_hotels-layout/amenities",
        "/_layout/_hotels-layout/categories",
        "/_layout/_hotels-layout/hotels_",
        "/_layout/_hotels-layout/locations",
        "/_layout/_hotels-layout/payments",
        "/_layout/_hotels-layout/profile"
      ]
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_auth-layout"
      ]
    },
    "/auth/_auth-layout": {
      "filePath": "auth/_auth-layout.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_auth-layout/login",
        "/auth/_auth-layout/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/_hotels-layout/amenities": {
      "filePath": "_layout/_hotels-layout/amenities.tsx",
      "parent": "/_layout/_hotels-layout"
    },
    "/_layout/_hotels-layout/categories": {
      "filePath": "_layout/_hotels-layout/categories.tsx",
      "parent": "/_layout/_hotels-layout"
    },
    "/_layout/_hotels-layout/hotels_": {
      "filePath": "_layout/_hotels-layout/hotels_.tsx",
      "parent": "/_layout/_hotels-layout"
    },
    "/_layout/_hotels-layout/locations": {
      "filePath": "_layout/_hotels-layout/locations.tsx",
      "parent": "/_layout/_hotels-layout"
    },
    "/_layout/_hotels-layout/payments": {
      "filePath": "_layout/_hotels-layout/payments.tsx",
      "parent": "/_layout/_hotels-layout"
    },
    "/_layout/_hotels-layout/profile": {
      "filePath": "_layout/_hotels-layout/profile.tsx",
      "parent": "/_layout/_hotels-layout"
    },
    "/auth/_auth-layout/login": {
      "filePath": "auth/_auth-layout/login.tsx",
      "parent": "/auth/_auth-layout"
    },
    "/auth/_auth-layout/": {
      "filePath": "auth/_auth-layout/index.tsx",
      "parent": "/auth/_auth-layout"
    },
    "/_layout/hotels/$hotelSlug": {
      "filePath": "_layout/hotels.$hotelSlug",
      "parent": "/_layout",
      "children": [
        "/_layout/hotels/$hotelSlug/_hotel-layout"
      ]
    },
    "/_layout/hotels/$hotelSlug/_hotel-layout": {
      "filePath": "_layout/hotels.$hotelSlug/_hotel-layout.tsx",
      "parent": "/_layout/hotels/$hotelSlug",
      "children": [
        "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)",
        "/_layout/hotels/$hotelSlug/_hotel-layout/rooms/",
        "/_layout/hotels/$hotelSlug/_hotel-layout/rooms/$roomId/"
      ]
    },
    "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)": {
      "filePath": "_layout/hotels.$hotelSlug/_hotel-layout/(hotel-info)",
      "parent": "/_layout/hotels/$hotelSlug/_hotel-layout",
      "children": [
        "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout"
      ]
    },
    "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout": {
      "filePath": "_layout/hotels.$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout.tsx",
      "parent": "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)",
      "children": [
        "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/amenities",
        "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/reviews",
        "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/rules",
        "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/"
      ]
    },
    "/_layout/hotels/$hotelSlug/_hotel-layout/rooms/": {
      "filePath": "_layout/hotels.$hotelSlug/_hotel-layout/rooms/index.tsx",
      "parent": "/_layout/hotels/$hotelSlug/_hotel-layout"
    },
    "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/amenities": {
      "filePath": "_layout/hotels.$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/amenities.tsx",
      "parent": "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout"
    },
    "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/reviews": {
      "filePath": "_layout/hotels.$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/reviews.tsx",
      "parent": "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout"
    },
    "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/rules": {
      "filePath": "_layout/hotels.$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/rules.tsx",
      "parent": "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout"
    },
    "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/": {
      "filePath": "_layout/hotels.$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout/index.tsx",
      "parent": "/_layout/hotels/$hotelSlug/_hotel-layout/(hotel-info)/_hotel-info-layout"
    },
    "/_layout/hotels/$hotelSlug/_hotel-layout/rooms/$roomId/": {
      "filePath": "_layout/hotels.$hotelSlug/_hotel-layout/rooms/$roomId/index.tsx",
      "parent": "/_layout/hotels/$hotelSlug/_hotel-layout"
    }
  }
}
ROUTE_MANIFEST_END */
